#!/usr/bin/env bash
# =================================================================================
# Script Name: 	grepIt
# By:		noodl3s
# Date:		April 3, 2013
# Purpose: 	to search for characters, phrases, or words
# Tested on:	Mac OSX 10.6.8
# Instructions:	1. save this script in the folder you would like to search within
#		2. in line 24, substitute '~/Sites/yourWebsiteFolder' for the path
#		   you would like to search within
#		3. save again
#		4. type 'chmod 777 ~/Sites/yourWebsiteFolder/grepIt' in a terminal
#		   to change permissions 
#		5. file is ready to use
# =================================================================================
clear
echo "Welcome to grepIt"
while [ "$phrase" != "q" ]; do
echo "Enter a phrase to search for OR type quit to end script:"
read phrase # read phrase
  if [ "$phrase" != "q" ]
  then
    clear
    echo "grepit search results for $phrase:"; grep -rli $phrase ~/Sites/yourWebsiteFolder | more
  else
    echo "goodbye!"; exit
  fi
done
